name: Android Develop branch CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: Decode Keystore & Generate local.properties
        env:
          RELEASE_STORE_BASE_64: ${{ secrets.RELEASE_STORE_BASE_64 }}
          KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          BITNAGIL_DEV_URL: ${{ secrets.BITNAGIL_DEV_URL }}
          BITNAGIL_PROD_URL: ${{ secrets.BITNAGIL_PROD_URL }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        run: |
          # Keystore Decoding
          echo $RELEASE_STORE_BASE_64 > encoded_keystore.txt
          base64 --decode encoded_keystore.txt > release.jks
          
          # Generate local.properties
          echo "kakao.native.app.key=$KAKAO_NATIVE_APP_KEY" >> local.properties
          echo "kakao.rest.api.key=$KAKAO_REST_API_KEY" >> local.properties
          echo "bitnagil.dev.url=$BITNAGIL_DEV_URL" >> local.properties
          echo "bitnagil.prod.url=$BITNAGIL_PROD_URL" >> local.properties
          echo "release.key.alias=$RELEASE_KEY_ALIAS" >> local.properties
          echo "release.key.password=$RELEASE_KEY_PASSWORD" >> local.properties
          echo "release.keystore.password=$RELEASE_STORE_PASSWORD" >> local.properties
          echo "release.keystore.path=../release.jks" >> local.properties

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}

      - name: Build and Verify
        run: ./gradlew ktlintCheck testDebugUnitTest assembleDebug
